// Public sources and interpretive limits stay alongside the in-game copy.
export const HISTORIC_STOPS = [
  { name: "Hospitaller headquarters", x: -3, z: -36,
    evidence: "EXCAVATED COMPLEX",
    text: "The Order of St John ran a hospital as well as a military headquarters. Its excavated court, wells and vaulted halls reveal how pilgrims and the sick were housed and supplied.",
    source: "https://www.akko.org.il/en/attraction/the-knights-halls/" },
  { name: "Montmusard", x: -58, z: -77,
    evidence: "DOCUMENTED QUARTER · RECONSTRUCTED STREETS",
    text: "The northern suburb expanded Acre beyond its older wall. Its own defenses enclosed homes and religious houses. These lanes and individual houses are a playable reconstruction.",
    source: "https://hadashot.iaa.org.il/report_detail_eng.aspx?id=1561" },
  { name: "Genoese merchants", x: -48, z: 22,
    evidence: "EXCAVATED WALLS & COVERED STREET",
    text: "Italian merchant communes had warehouses, churches and their own defended quarters. Genoese fortifications and a covered street survive beneath later buildings. The War of Saint Sabas began after our setting, in 1256.",
    source: "https://hadashot.iaa.org.il/Report_Detail_Eng.aspx?id=25261&mag_id=125" },
  { name: "Cathedral of the Holy Cross", x: -3, z: -16,
    evidence: "DOCUMENTED CHURCH · INTERPRETED ELEVATION",
    text: "The cathedral lay south of the Hospitaller headquarters. Its location is historically grounded; the roof, tower and facade here are an interpretation, not a surviving elevation.",
    source: "https://www.akko.org.il/en/attraction/the-knights-halls/" },
  { name: "Templar fortress", x: -59, z: 58,
    evidence: "DOCUMENTED SEA FORTRESS",
    text: "The Templars occupied Acre’s southwestern seafront. Their fortified headquarters stood at the western end of the passage to the port. Hold E at the stair to explore the tunnel.",
    source: "https://www.akko.org.il/en/attraction/the-templars-tunnel/" },
  { name: "Pisan quarter", x: -34, z: 62,
    evidence: "DOCUMENTED QUARTER",
    text: "The passage from the Templar fortress to the port runs beneath the Pisan quarter. Merchant lodging, storage and trade connected this part of the city to the Mediterranean.",
    source: "https://www.akko.org.il/en/attraction/the-templars-tunnel/" },
  { name: "Venetian waterfront", x: 58, z: 22,
    evidence: "DOCUMENTED COMMERCIAL QUARTER",
    text: "Acre was a port of pilgrims and merchants as well as soldiers. Venetian properties combined storage, shops and lodging. The cargo and buildings here interpret that working waterfront.",
    source: "https://cornellpress.manifoldapp.org/read/aa2b50d1-da8d-46f0-b699-f90dc8ab86e7/section/2f894fa7-353e-4f88-8b1a-29afb82a8515" },
  { name: "Harbour & sea passage", x: 37, z: 64,
    evidence: "RECONSTRUCTED MEDIEVAL HARBOUR",
    text: "Quays, moles and a controlled entrance protected maritime trade. Later views disagree about the basin’s shape. The modern Ottoman waterfront is not a direct plan of the port in 1250.",
    source: "https://www.mgh-bibliothek.de/dokumente/a/a051143.pdf" },
];

export const SETTING_NOTE = "Acre, c. 1250: a living port of the Latin Kingdom of Jerusalem, before the War of Saint Sabas (1256–58) and the siege of 1291. Major places follow archaeology and historical plans; streets, elevations, patrols and the dispatch mission are reconstructed or fictional.";
